run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosimple
    - staticcheck
    - unused
    - govet
    - ineffassign
    - gocritic

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0